import {
  Archive,
  ArrowLeftRight,
  Book,
  BookOpen,
  Bot,
  Box,
  Bug,
  ChartLine,
  CircleHelp,
  Cloud,
  Code,
  Compass,
  CreditCard,
  Crosshair,
  Database,
  FileText,
  FlaskConical,
  Folder,
  FolderOpen,
  Gauge,
  Globe,
  Grid2x2,
  Info,
  Laptop,
  Layers,
  Lightbulb,
  Lock,
  Network,
  Plug,
  Puzzle,
  RefreshCw,
  Repeat,
  Rocket,
  Route,
  Shield,
  SlidersHorizontal,
  Sparkles,
  Star,
  Tag,
  Terminal,
  UserCog,
  Users,
  Wallet,
  Wrench,
} from "lucide-react";

const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  // Meta / section icons
  compass: Compass,
  "book-open": BookOpen,
  bot: Bot,
  code: Code,
  box: Box,
  route: Route,
  shield: Shield,
  wrench: Wrench,
  users: Users,
  terminal: Terminal,
  sparkles: Sparkles,
  lightbulb: Lightbulb,

  // Page frontmatter icons
  "puzzle-piece": Puzzle,
  book: Book,
  "shield-halved": Shield,
  robot: Bot,
  plug: Plug,
  "file-lines": FileText,
  database: Database,
  "chart-line": ChartLine,
  "arrows-rotate": RefreshCw,
  "arrow-right-arrow-left": ArrowLeftRight,
  wallet: Wallet,
  "vial-circle-check": FlaskConical,
  "users-gear": UserCog,
  tag: Tag,
  stripe: CreditCard,
  star: Star,
  sliders: SlidersHorizontal,
  rocket: Rocket,
  repeat: Repeat,
  question: CircleHelp,
  "network-wired": Network,
  lock: Lock,
  globe: Globe,
  "gauge-high": Gauge,
  "folder-open": FolderOpen,
  folder: Folder,
  cube: Box,
  crosshairs: Crosshair,
  cloud: Cloud,
  "circle-info": Info,
  bug: Bug,
  "boxes-stacked": Layers,
  "box-archive": Archive,
  "grid-2": Grid2x2,
  "laptop-code": Laptop,
  "layer-group": Layers,
};

export function DocsSidebarIcon({ icon }: { icon?: string }) {
  const Icon = icon ? iconMap[icon] : null;
  if (!Icon) return null;
  return <Icon className="size-4 shrink-0 text-fd-muted-foreground" />;
}
