[package]
name = "pemrix-faucet"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
description = "PEMRIX testnet faucet service."

[[bin]]
name = "pemrix-faucet"
path = "src/main.rs"

[dependencies]
pemrix-primitives = { workspace = true }
pemrix-crypto = { workspace = true }
pemrix-sdk = { workspace = true }
pemrix-rpc = { workspace = true }
pemrix-testnet = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
clap = { workspace = true }

[dev-dependencies]
tower = { workspace = true }
