[package]
name = "pemrix-vm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
description = "Execution layer and WASM-based smart contract VM for PEMRIX."

[dependencies]
pemrix-primitives = { workspace = true }
pemrix-storage = { workspace = true }
pemrix-crypto = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[features]
default = []
wasm = ["dep:wasmtime"]

[dependencies.wasmtime]
version = "36.0.14"
optional = true

[dev-dependencies]
